/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsideLayout: typeof import('./components/layout/AsideLayout.vue')['default']
    DefaultLayout: typeof import('./components/layout/DefaultLayout.vue')['default']
    HeaderLayout: typeof import('./components/layout/HeaderLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./components/snackBar/SnackBar.vue')['default']
    WatchLog: typeof import('./components/WatchLog.vue')['default']
  }
}
