name: ci

on: [push]

jobs:
  eletron:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build: "build:linux"
            suffix: deb
          - os: windows-latest
            build: "build:win"
            suffix: exe
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false
          ref: feature-1.2.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      
      - name: Get version
        id: package
        uses: actions/github-script@v5
        with:
          script: |
            const package = require('./package.json')
            return package.version

      - name: Output version
        run: | 
          eval echo "The version is ${{ steps.package.outputs.result }}"
        env: 
          VERSION: eval echo "v${{ steps.package.outputs.result }}"
          
      - name: Check verison
        run: echo "${VERSION}"
          
      - name: Build
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ steps.package.outputs.result }}
          build_script_name: ${{ matrix.build }}

      - name: Check Build
        run: ls ${{ github.workspace }}/release

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: ${{ format('{0}', github.repository) }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./release/**/*.${{ matrix.suffix }}
          overwrite: true
          tag: ${{ env.VERSION }}
